### ISSUE TITLE
NoSuchMethodError exception during class initialization

### ISSUE THREAD

**Issue by rvprasad** [holgerbrandl/kscript#276]
Executing the following script results in *NoSuchMethodError* exception during class initialization. 

**Code**
```kotlin
// test.kts
@file:DependsOn("com.github.ajalt:clikt:2.8.0")

import kotlin.reflect.KProperty

class Delegate() {
  operator fun getValue(t: Any?, p: KProperty<*>) = 3
}

internal class Main {
    private val a by Delegate()
}

Main()
```

**Environment**
- Ubuntu 20.04
- java: 8.0.265-zulu (via sdkman)
- kotlin: 1.4.0 (via sdkman)
- kscript: 2.9.3 (via sdkman)

**Command**
```kscript test.kts```

**Output**
```
[kscript] Resolving dependencies...
[kscript]     Resolving com.github.ajalt:clikt:2.8.0...Done
[kscript]     Resolving com.github.holgerbrandl:kscript-annotations:1.4...Done
[kscript] Dependencies resolved
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at Main_Test$Companion.main(Main_Test.kt:6)
	at Main_Test.main(Main_Test.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:149)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:159)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at Test$Main.<clinit>(test.kts)
	at Test.<init>(test.kts:13)
	... 13 more
```

**Comment by rvprasad** [comment]
Interestingly, removing the redundant import or the private property declaration fixes the exception.

**Comment by rvprasad** [comment]
For the above code, the package generated via `--package` executes without this failure/exception.

**Comment by rvprasad** [comment]
This issue was caused because Clikt library was dependent on Kotlin 1.3.72 and `kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V` was introduced in Kotlin 1.4.0.  It will likely be resolved when Clikt is updated to work with Kotlin 1.4.0.
