### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MarcinMoskala** [holgerbrandl/kscript#15]
Hey, I installed it on mac exactly like in instructions. Not in /bin because it is not permitted in new mac, but in another folder and I added it to PATH, but when I start any script using kscript I get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/script/templates/standard/ScriptTemplateWithArgs
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Main_Hello.main(Main_Hello.java:4)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:60)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:104)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:110)
Caused by: java.lang.ClassNotFoundException: kotlin.script.templates.standard.ScriptTemplateWithArgs
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```

**Comment by holgerbrandl** [comment]
Sorry for inconvenience. What version of kotlin are you using? Just type
```bash
 kotlinc -version
```

**Comment by MarcinMoskala** [comment]
MBP-MarcinMac:~ marcin$  kotlinc -version
info: Kotlin Compiler version 1.1.0-rc-91

**Comment by holgerbrandl** [comment]
Indeed `kscript` is not yet working with 1.1. Unfortunately this seems more an issue with Kotlin itself, and I have filed a ticket for the problem: 
https://youtrack.jetbrains.com/issue/KT-16562

Feel welcome to vote for it, because JB is more likely to act upon it if there are some votes.

**Comment by holgerbrandl** [comment]
They suggested a workaround and I will release a patched version of `kscript` later today or tomorrow.

**Comment by holgerbrandl** [comment]
I've released kscript v1.2 this morning which should solve the problem. You can run the auto-update with
```bash
kscript --self-update
```
Feel welcome if you have other issues when using `kscript`

**Comment by chocolateboy** [comment]
I'm getting the same error on Linux:

kscript: 1.2 (15c7cc4)
kotlin: 1.1.1
OS: Linux (Arch)

```
$ kscript --clear-cache
Cleaning up cache...
$ cat hello.kt
println("Hello, world!")
$ kscript hello.kt
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/script/templates/standard/ScriptTemplateWithArgs
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at Main_Kscript_stdin_e159f6.main(Main_Kscript_stdin_e159f6.java:4)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:60)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:104)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:110)
Caused by: java.lang.ClassNotFoundException: kotlin.script.templates.standard.ScriptTemplateWithArgs
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```
kotlinc is installed correctly and compiles scripts OK.

**Comment by chocolateboy** [comment]
I see the [fix](https://github.com/holgerbrandl/kscript/commit/d657d9dfea41b129a28a48354b41841591700853) makes use of `KOTLIN_HOME`. It's not set on my system, but setting it fixes the problem:

```
$ KOTLIN_HOME=/usr/share/kotlin kscript hello.kt
Hello, world!
```

It could be a safe default if it's not defined:

```diff
-exec kotlin ${kotlin_opts} -classpath ${jarFile}:${KOTLIN_HOME}/lib/kotlin-script-runtime.jar:"$classpath" Main_${className} "$@"
+exec kotlin ${kotlin_opts} -classpath ${jarFile}:${KOTLIN_HOME:-/usr/share/kotlin}/lib/kotlin-script-runtime.jar:"$classpath" Main_${className} "$@"
```

Alternatively, you could adopt the [same approach as kotlin-script](https://github.com/andrewoma/kotlin-script/blob/78f4f730ec659a3e1c75b21deaf1b260d1d08248/kotlins#L29-L45).

Or possibly even scrape it out of kotlinc e.g.:

```
$ JAVACMD=echo kotlin
-Xmx256M -Xms32M -Dkotlin.home=/usr/share/kotlin -cp /usr/share/kotlin/lib/kotlin-runner.jar org.jetbrains.kotlin.runner.Main
```

**Comment by holgerbrandl** [comment]
Thanks for the hint.

**Comment by chocolateboy** [comment]
Thanks, but that [particular solution](https://github.com/holgerbrandl/kscript/blob/01d6b36c1797ad666272d10350712d09dd72ca60/kscript#L191-L194) doesn't work on my system:

    $ KOTLIN_HOME="$(dirname $(which kotlinc))/.." 
    $ readlink -f $KOTLIN_HOME
    /usr

That means it looks for the JAR in:

    $ echo ${KOTLIN_HOME}/lib/kotlin-script-runtime.jar
    /usr/lib/kotlin-script-runtime.jar

Rather than where it actualy resides:

    /usr/share/kotlin/lib/kotlin-script-runtime.jar

Like I say, the correct path can be exposed by the kotlinc script (or its kotlin wrapper) if you don't mind doing a bit of light scraping:

> $ JAVACMD=echo kotlin
> -Xmx256M -Xms32M -Dkotlin.home=**<span style="lasrger">/usr/share/kotlin</span>** -cp /usr/share/kotlin/lib/kotlin-runner.jar org.jetbrains.kotlin.runner.Main

**Comment by holgerbrandl** [comment]
Just out of curiosity. How did kotlin end up under /usr/share/? homebrew? I always use sdkman which just dumps it in a hidden directory in the user home.

I'd think it would be better to avoid another JVM launch (which costs another few hundred milliseconds). Especially for small inlined command-line tools this may make a difference for some users.

So what about (see also latest commit):
``` 
if [[ $OSTYPE != darwin* ]]; then minusFarg="-f"; fi
abspath() { echo "$(readlink ${minusFarg} $1)"; }
ll $(dirname $(abspath $(which kotlinc)))/../lib/kotlin-script-runtime.jar
```

**Comment by chocolateboy** [comment]
> Just out of curiosity. How did kotlin end up under /usr/share/

It's a [standard location](https://wiki.archlinux.org/index.php/Arch_packaging_standards) on Arch Linux.

> I'd think it would be better to avoid another JVM launch

It doesn't launch the JVM:

    $ time KOTLIN_RUNNER=1 JAVACMD=echo kotlinc
    real	0m0.012s
    user	0m0.000s
    sys	0m0.000s

> So what about (see also latest commit):

    ls: cannot access '/usr/bin/../lib/kotlin-script-runtime.jar': No such file or directory

**Comment by holgerbrandl** [comment]
Thanks for your patience. Could you try again. I've changed it to 
```
    KOTLIN_HOME=$(dirname $(dirname $(JAVACMD=echo kotlin  |  awk 'NR>1' RS=' ' | grep kotlin-runner)))
```

**Comment by chocolateboy** [comment]
> Could you try again. 

Yes, that works. Thanks!

> I'm still confused/amazed by JAVACMD=echo kotlin. It looks like a variable assignment but it somehow resolves kotlin?

It's just an environment variable assignment, the same as running:

```bash
env JAVACMD=echo kotlin
```

or setting:

```bash
JAVACMD=echo
```

in [kotlinc](https://github.com/JetBrains/kotlin/blob/build-1.1.3-dev-1413/compiler/cli/bin/kotlinc).

The `kotlin` wrapper sets `KOTLIN_RUNNER=1`, which selects a branch at the end of `kotlinc`, which defines `java_args`, which defines the `kotlin.home` property. On my system, it's faster to run `kotlinc` directly as shown above:

```bash
$ time JAVACMD=echo kotlin
real	0m0.019s
user	0m0.000s
sys	0m0.000s

$ time KOTLIN_RUNNER=1 JAVACMD=echo kotlinc
real	0m0.012s
user	0m0.000s
sys	0m0.000s
```

`kotlinc` allows the path to `java` to be supplied via the [JAVACMD envirionment variable](https://github.com/JetBrains/kotlin/blob/build-1.1.3-dev-1413/compiler/cli/bin/kotlinc#L82):

```bash
"${JAVACMD:=java}" $JAVA_OPTS "${java_args[@]}" -cp "${kotlin_app[@]}" "${kotlin_args[@]}"
```

If not supplied it defaults to `java`. We abuse this to replace `java` with `echo`, so the last line of `kotlinc` becomes:

```
echo $JAVA_OPTS "${java_args[@]}" -cp "${kotlin_app[@]}" "${kotlin_args[@]}"
```

This prints out the `kotlin.home` property via `java_args`:

```bash
    java_args=("${java_args[@]}" "-Dkotlin.home=${KOTLIN_HOME}")
```

IMO, it's safer to just use the defined `kotlin.home` property rather than scraping the name of a JAR file, which might be replaced/renamed. Putting this together gives:

```bash
$ KOTLIN_HOME=$(KOTLIN_RUNNER=1 JAVACMD=echo kotlinc | awk 'NR>1' RS=' ' | grep -F kotlin.home= | cut -d= -f2)
$ echo $KOTLIN_HOME
/usr/share/kotlin
```

**Comment by holgerbrandl** [comment]
Thanks for the nice explanation. I've changed it accordingly.
