### ISSUE TITLE
kscript doesn't appear to work with Clikt and Kotlin 1.4.10

### ISSUE THREAD

**Issue by kenyee** [holgerbrandl/kscript#279]
I get this cryptic NoSuchMethodError with Kotlin 1.4.10...works fine if I back down to 1.3.72

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at Main_Scriptlet_a9f5a3bb1e4ba312$Companion.main(Main_Scriptlet_a9f5a3bb1e4ba312.kt:6)
	at Main_Scriptlet_a9f5a3bb1e4ba312.main(Main_Scriptlet_a9f5a3bb1e4ba312.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:149)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:159)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at Scriptlet_a9f5a3bb1e4ba312$SonarqubeAnalyzer.<clinit>(scriptlet.a9f5a3bb1e4ba312.kts)
```

**Comment by holgerbrandl** [comment]
Could you provide a short example?

**Comment by kenyee** [comment]
[kscript14bug.zip](https://github.com/holgerbrandl/kscript/files/5357380/kscript14bug.zip)

Run that with Docker after unzipping it into a directory:
docker build . -t kscriptbug

You can change the Kotlin version to 1.3.72 and it works fine.  I set it up as a Docker build so you know it's a fully clean environment to repro this in.

**Comment by helios175** [comment]
I had the same issue. I wonder if we can somehow tell kscript to use certain version of kotlin. I'm not sure how that can be configured either in kscript or in my environment as a whole.

What I found so far:

- It happened inconsistently – it worked for me until I tried reinstalling kscript to help a coworker and I had it again.
- If I remove the `by option(...)` stuff it will work. It seems that the code needs a `PropertyReference1Impl` constructor with only two arguments and that's not present in Kotlin 1.4 at least (it always receives 3 args).

**Comment by kenyee** [comment]
Also tried using argparser:
https://github.com/xenomachina/kotlin-argparser

and same issue...looks like they both use the same technique...

**Comment by martinbonnin** [comment]
`public PropertyReference1Impl(Class owner, String name, String signature, int flags)` is only available since Kotlin 1.4:

https://github.com/JetBrains/kotlin/blob/master/libraries/stdlib/jvm/runtime/kotlin/jvm/internal/PropertyReference1Impl.java#L22

Which would hint at the wrong stdlib being in the classpath?

**Comment by holgerbrandl** [comment]
Indeed, something is wrong in the classpath. IMHO its clearly clikt to blame here. See https://repo1.maven.org/maven2/com/github/ajalt/clikt/2.7.1/clikt-2.7.1.pom
Since it is relying on kotlin 1.3.72 (see dependencies section) it brings a wrong outdated stdlib into the classpath. 

When removing 1.3.72 manually from the classpath in the example when running it via kscript, the example works fine for me.

I guess clikt would need to be published with kotlin-stdlib as compile-only and not runtime dependency.

FYI @ajalt 

@kenyee It's quite a coincidence that kotlin-argparser seems to suffer from the same problem.

**Comment by martinbonnin** [comment]
> Since it is relying on kotlin 1.3.72 (see dependencies section) it brings a wrong outdated stdlib into the classpath.

`Clikt` having `1.3.72` as a compile dependency shouldn't prevent other consumers like kscript here to substitute `1.4.10` at runtime. From my understanding, this is the [default Gradle behaviour](https://docs.gradle.org/current/userguide/dependency_management.html#understanding_dependency_resolution): `If no ranges are involved, then the highest version that is not rejected will be selected`. 

@kenyee could you workaround the issue by specifying stdlib explicitely? 

```
@file:@DependsOn("org.jetbrains.kotlin:kotlin-stdlib:1.4.10")
```

If that works, it would be nice to tweak kscript dependency resolutions to allow "upgrading" the versions in this case

**Comment by holgerbrandl** [comment]
I'd rather think that clikt should add the stdlib as compileOnly. See https://docs.gradle.org/current/userguide/java_library_plugin.html

This may be just problematic if a library is intended to be used with java directly without kotlin being involved. If so, the library developer would be correct in using a compile/api declaration on the stdlib. Not sure what the recommended best practice is.

kscript will always run scripts with kotlin executable (and thus including the corresponding version of the stdlib). It must be (and is) unopinionated about dependencies and will resolve them as defined in the artifact descriptors (pom-files).

**Comment by martinbonnin** [comment]
> kscript will always run scripts with kotlin executable (and thus including the corresponding version of the stdlib).

Then I would expect `kotlin-stdlin:1.4.10` in the classpath there? 

> It must be (and is) unopinionated about dependencies and will resolve them as defined in the artifact descriptors (pom-files).

But ultimately both the compiled script and the dependencies share the same classpath, right? If `kscript` compiles `main.kts` against `1.4.70` and some depencency declares `1.3.72` in the compile classpath, which should win?

**Comment by holgerbrandl** [comment]
I think when running `kotlin` it adds the corresponding version of stdlib by default. The docs are very clear in the case of kotlinc, see https://kotlinlang.org/docs/reference/compiler-reference.html#-no-stdlib. For `kotlin` I could not find a direct reference, except for
```kotlin -help
kotlin: run Kotlin programs, scripts or REPL.

Usage: kotlin <options> <command> <arguments>
where command may be one of:
  foo.Bar                    Runs the 'main' function from the class with the given qualified name
  app.jar                    Runs the given JAR file as 'java -jar' would do
                             (-classpath argument is ignored and no Kotlin runtime is added to the classpath)
and possible options include:
  -classpath (-cp) <path>    Paths where to find user class files
  -Dname=value               Set a system JVM property
```
I'd understand that such as _a Kotlin runtime is added to the classpath_ when a class name is provided as  argument.

So I'd guess that having 2 conflicting stdlibs in the classpath is causing the problem.

I rather think that `kscript` is already compiling against the classpath with both stdlibs.

I do not know which jar has precedence, it's up to the used classloader to decide I think. And kotlin is using not the default JVM classloader afaik.

@ligee Can you help to shed some light (a) on library development stdlib ex/inclusion best practice, and (b) kotlin internal conflict management when having 2 conflicting stdlibs in the classpath for compilation & runtime?

**Comment by martinbonnin** [comment]
What about adding the kotlin stdlib from the installed kotlin distribution to the `aether` resolution algorithm explicitely? If `aether` uses the same principles as Gradle, I think that should "upgrade" the stdlib dependency for everyone?

**Comment by kenyee** [comment]
> @kenyee could you workaround the issue by specifying stdlib explicitely?
> 
> ```
> @file:@DependsOn("org.jetbrains.kotlin:kotlin-stdlib:1.4.10")
> ```

FYI, tried this:
sdkman use kotlin 1.4.10
kscript --clear-cache
./sonarqube_status.kts --help

and same error, so this doesn't work:
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V

This is indeed a weird one...
Also, I thought 1.4.10 doesn't require the stdlib in the classpath any more?  It automagically adds it in app gradle files.

**Comment by martinbonnin** [comment]
> Also, I thought 1.4.10 doesn't require the stdlib in the classpath any more? It automagically adds it in app gradle files.

The stdlib is definitely still needed in the JVM runtime classpath. What changed is that the Kotlin plugin adds it to the Gradle dependencies automatically by default: https://github.com/JetBrains/kotlin/blob/07aee8831eb45690053028f39f3312e1c8e90f69/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/KotlinDependenciesManagement.kt#L60

**Comment by holgerbrandl** [comment]
> What about adding the kotlin stdlib from the installed kotlin distribution to the aether resolution algorithm explicitly?  
I think there is no need, it's added by `kotlin` executable by default.


Kscript is not using gradle (unless `--idea` is being used to create a temporary script project), it simply resolves declared dependencies with aether (and more recently also the kotlin resolver API).
And since there is not even an option to not include the stdlib when calling `kotlin` in https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/Kscript.kt#L284 the kotlin core team does not seem to consider it a sensible option to exclude stdlib when running applications.

I'd deployed a simple test project with v1.4.10 of the kotlin gradle plugin, and this is what I find
* no dependency being declared --> installed pom does not list stdlib but gradle still links stdlib for compiling
* compileOnly dependency on stdlib --> installed pom does not list stdlib 
* compile dependency on stdlib --> install pom lists stdlib
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.github.holgerbrandl</groupId>
  <artifactId>kscript-annotations</artifactId>
  <version>1.7-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
      <version>1.4.10</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```

To me this this seems like a correct behavior. **tldr** It's the obligation of a library vendor to correctly use no dependency on stdlib or compileOnly. If so, the library can be used with `kotlin` or `kscript` without any stdlib version conflicts.

**Comment by ligee** [comment]
@holgerbrandl in contrast to gradle, maven, and other advanced build systems, the `kotlin`/`kotlinc` tools do not offer any classpath conflict management. Basically, the first jar in the classpath wins, or so. 
The `kotlinc` has the `-no-stdlib` and `-no-reflect` options, which allow specifying the stdlib/reflect explicitly in the classpath, but that's about it. 
The `kotlin` runner, unfortunately, has even less - only `-no-reflect`. Maybe `-no-stdlib` should be added there too, but seems we weren't aware of any demand for that until now.

So, at the moment, the simplest solution I can think of is to use `kotlinc` instead of `kotlin` in the `kscript` and use `-no-stdlib` to handle stdlib conflicts.

**Comment by kenyee** [comment]
Using kotlinc in kscript seems like a reasonable workaround 😃 

In the meantime, if folks hit this, you can use the Apache Commons CLI arg parser.
It's a bit more crude and verbose than Clikt (namely no Env var support) but works fine otherwise.  Use this artifact:

```
@file:DependsOn("commons-cli:commons-cli:1.4")
```

**Comment by holgerbrandl** [comment]
@ligee 
* I think `kotlinc` can't be used here because it is meant to compile code and not to run it.  E.g. there is afaik no way to define the application entrypoint.
* Indeed, adding `-no-stdlib` to `kotlin` would allow a version agnostic usage, where dependencies declare what version of the stdlib to use, which is - as I have learnt in this thread - the new default enforced by the gradle kotlin plugin. So to me  `-no-stdlib` for `kotlin` would be the natural followup to support this new default policy.

@kenyee Nobody wants argparser anylonger :-) With kscript [v3.0](https://github.com/holgerbrandl/kscript/blob/master/NEWS.md#30) `clikt` works at least when matching a configuration (version 1.4.10 of kotlin being installed and clikt compiled against 1.4.10) is being used. See [examples/clikt-example.kts](https://github.com/holgerbrandl/kscript/blob/master/examples/clikt-example.kts)

```
brandl@ubuntu2:kscript$ kscript --version
kscript - Enhanced scripting support for Kotlin on *nix-based systems.

Usage:
 kscript [options] <script> [<script_args>]...
 kscript --clear-cache

The <script> can be a  script file (*kts), a script URL, - for stdin, a *.kt source file with a main method, or some kotlin code.

Use '--clear-cache' to wipe cached script jars and urls

Options:
 -i --interactive        Create interactive shell with dependencies as declared in script
 -t --text               Enable stdin support API for more streamlined text processing
 --idea                  Open script in temporary Intellij session
 -s --silent             Suppress status logging to stderr
 --package               Package script and dependencies into self-dependent binary
 --add-bootstrap-header  Prepend bash header that installs kscript if necessary


Copyright : 2020 Holger Brandl
License   : MIT
Version   : v3.0.2
Website   : https://github.com/holgerbrandl/kscript
Kotlin    : 1.4.10-release-411
Java      : JRE 11.0.9+11
brandl@ubuntu2:kscript$ kscript examples/clikt-example.kts 
Your name: 
```
To me, this solution solves the described issue sufficiently well, so I'm closing this ticket for now. Feel welcome to reopen if needed.

**Comment by ligee** [comment]
@holgerbrandl I think there are quite easy workarounds that would allow using `kotlinc`, the entry point is detected automatically if you have a single `main` function, and if it doesn't work for some reasons, the runner code is not really sophisticated. But of course, adding `-no-stdlib` to `kotlin` runner is a good idea. I created an issue about it - https://youtrack.jetbrains.com/issue/KT-43294.

**Comment by kenyee** [comment]
confirmed this fixes it...thanks :-)
Starred the youtrack issue too :-)

**Comment by kenyee** [comment]
apparently, it doesn't fix it...I got into a bad state again by switching kotlin from 1.4.10 to 1.3.72 and back.

Same error:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at Main_Scriptlet_dfc6de29a95db418$Companion.main(Main_Scriptlet_dfc6de29a95db418.kt:6)
	at Main_Scriptlet_dfc6de29a95db418.main(Main_Scriptlet_dfc6de29a95db418.kt)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jetbrains.kotlin.runner.AbstractRunner.run(runners.kt:64)
	at org.jetbrains.kotlin.runner.Main.run(Main.kt:149)
	at org.jetbrains.kotlin.runner.Main.main(Main.kt:159)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.PropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at Scriptlet_dfc6de29a95db418$AppDirCli.<clinit>(scriptlet.dfc6de29a95db418.kts)
	at Scriptlet_dfc6de29a95db418$Startup$Companion.main(scriptlet.dfc6de29a95db418.kts:134)
	at Scriptlet_dfc6de29a95db418.<init>(scriptlet.dfc6de29a95db418.kts:165)
	... 13 more
```

Version info from kscript:
Copyright : 2020 Holger Brandl
License   : MIT
Version   : v3.0.2
Website   : https://github.com/holgerbrandl/kscript
Kotlin    : 1.4.10-release-411
Java      : JRE 1.8.0_242

Basically the same issue I think... it's somehow using the kotlin 1.3 stdlib but it's Kotlin 1.4.
Doing sdk uninstall kotlin 1.3.72 does not help :-(

The difference now is that doing
sdk use kotlin 1.3.72 doesn't make this work...

**Comment by holgerbrandl** [comment]
Hmm, I've tried to switch back and further the used version of kotlin with `sdk use` but I can not reproduce the problem yet. It just seems to work fine.

Could you clear the cache `--clear-cache` once and maybe check with `--version` that indeed the correction version of kotlin is being used by kscript?

**Comment by kenyee** [comment]
I did that before I printed the version info above.
I'm a bit puzzled how I got it into this state as well....tried using sdk man to switch kotlin 1.3.72 and 1.4.10 back and forth w/ the same problem.  Did kscript --version and kotlin -version to confirm.

I suspect once we switch to -no-stdlib in the kotlin runner, this will no longer happen.

**Comment by holgerbrandl** [comment]
I'm not sure how to proceed here. In order to do so, we'd need to find a way for me to reproduce the problem.

**Comment by kenyee** [comment]
Can leave this closed...I'll see if I can figure out how to repro this in a docker container so the test environment is consistent.
